import React, {Component} from 'react';

class GridBall extends Component {
  render() {
    return (
      <div className="row">
        <table className="table table-bordered col-sm-12 col-md-12 col-lg-12">
          <tbody>
            <tr>
              <th>B</th>
              <td>{this.props.notInBalls(1)}</td>
              <td>{this.props.notInBalls(2)}</td>
              <td>{this.props.notInBalls(3)}</td>
              <td>{this.props.notInBalls(4)}</td>
              <td>{this.props.notInBalls(5)}</td>
              <td>{this.props.notInBalls(6)}</td>
              <td>{this.props.notInBalls(7)}</td>
              <td>{this.props.notInBalls(8)}</td>
              <td>{this.props.notInBalls(9)}</td>
              <td>{this.props.notInBalls(10)}</td>
              <td>{this.props.notInBalls(11)}</td>
              <td>{this.props.notInBalls(12)}</td>
              <td>{this.props.notInBalls(13)}</td>
              <td>{this.props.notInBalls(14)}</td>
              <td>{this.props.notInBalls(15)}</td>
            </tr>
            <tr>
              <th>I</th>
              <td>{this.props.notInBalls(16)}</td>
              <td>{this.props.notInBalls(17)}</td>
              <td>{this.props.notInBalls(18)}</td>
              <td>{this.props.notInBalls(19)}</td>
              <td>{this.props.notInBalls(20)}</td>
              <td>{this.props.notInBalls(21)}</td>
              <td>{this.props.notInBalls(22)}</td>
              <td>{this.props.notInBalls(23)}</td>
              <td>{this.props.notInBalls(24)}</td>
              <td>{this.props.notInBalls(25)}</td>
              <td>{this.props.notInBalls(26)}</td>
              <td>{this.props.notInBalls(27)}</td>
              <td>{this.props.notInBalls(28)}</td>
              <td>{this.props.notInBalls(29)}</td>
              <td>{this.props.notInBalls(30)}</td>
            </tr>
            <tr>
              <th>N</th>
              <td>{this.props.notInBalls(31)}</td>
              <td>{this.props.notInBalls(32)}</td>
              <td>{this.props.notInBalls(33)}</td>
              <td>{this.props.notInBalls(34)}</td>
              <td>{this.props.notInBalls(35)}</td>
              <td>{this.props.notInBalls(36)}</td>
              <td>{this.props.notInBalls(37)}</td>
              <td>{this.props.notInBalls(38)}</td>
              <td>{this.props.notInBalls(39)}</td>
              <td>{this.props.notInBalls(40)}</td>
              <td>{this.props.notInBalls(41)}</td>
              <td>{this.props.notInBalls(42)}</td>
              <td>{this.props.notInBalls(43)}</td>
              <td>{this.props.notInBalls(44)}</td>
              <td>{this.props.notInBalls(45)}</td>
            </tr>
            <tr>
              <th>G</th>
              <td>{this.props.notInBalls(46)}</td>
              <td>{this.props.notInBalls(47)}</td>
              <td>{this.props.notInBalls(48)}</td>
              <td>{this.props.notInBalls(49)}</td>
              <td>{this.props.notInBalls(50)}</td>
              <td>{this.props.notInBalls(51)}</td>
              <td>{this.props.notInBalls(52)}</td>
              <td>{this.props.notInBalls(53)}</td>
              <td>{this.props.notInBalls(54)}</td>
              <td>{this.props.notInBalls(55)}</td>
              <td>{this.props.notInBalls(56)}</td>
              <td>{this.props.notInBalls(57)}</td>
              <td>{this.props.notInBalls(58)}</td>
              <td>{this.props.notInBalls(59)}</td>
              <td>{this.props.notInBalls(60)}</td>
            </tr>
            <tr>
              <th>O</th>
              <td>{this.props.notInBalls(61)}</td>
              <td>{this.props.notInBalls(62)}</td>
              <td>{this.props.notInBalls(63)}</td>
              <td>{this.props.notInBalls(64)}</td>
              <td>{this.props.notInBalls(65)}</td>
              <td>{this.props.notInBalls(66)}</td>
              <td>{this.props.notInBalls(67)}</td>
              <td>{this.props.notInBalls(68)}</td>
              <td>{this.props.notInBalls(69)}</td>
              <td>{this.props.notInBalls(70)}</td>
              <td>{this.props.notInBalls(71)}</td>
              <td>{this.props.notInBalls(72)}</td>
              <td>{this.props.notInBalls(73)}</td>
              <td>{this.props.notInBalls(74)}</td>
              <td>{this.props.notInBalls(75)}</td>
            </tr>
          </tbody>
        </table>
      </div>
    );
  }
}

export default GridBall;
